import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next";
import { FC } from "react";

type Props = {
  serverTime: string;
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  res,
}) => {
  res.setHeader(
    "Cache-Control",
    "public, max-age=10, stale-while-revalidate=60"
  );

  const time = new Date();
  const serverTime = `${String(time.getHours()).padStart(2, "0")}:${String(
    time.getMinutes()
  ).padStart(2, "0")}:${String(time.getSeconds()).padStart(2, "0")}`;

  return {
    props: {
      serverTime: serverTime,
    },
  };
};

const Page: FC<Props> = ({ serverTime }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description} id="message">
          <p>
            This page was created: <strong>{serverTime}</strong>
          </p>
        </div>
      </main>
    </>
  );
};

export default Page;
